openapi: 3.2.0
info:
  title: Eliq Data Management Client details API
  description: '# API Reference


    The Eliq data management API is organized around REST.'
  contact:
    name: Support
    email: support_b2b@eliq.com
  version: 1.5.2
tags:
- name: Client - Details
paths:
  /client-details/available-languages:
    get:
      tags:
      - Client - Details
      summary: Gets available languages for the users
      operationId: get-availablelanguages
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
              examples:
                Mutiple available languages:
                  value:
                  - nl-BE
                  - en-GB
                  - fr-FR
                  - de-DE
                Single available language:
                  value:
                  - en-GB
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
              examples:
                Mutiple available languages:
                  value:
                  - nl-BE
                  - en-GB
                  - fr-FR
                  - de-DE
                Single available language:
                  value:
                  - en-GB
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
              examples:
                Internal server error. If problem remains, please contact support:
                  value:
                    code: INTERNAL_ERROR
                    description: Internal server error. If problem remains, please contact support
                    request_id: 65e2ea86-470f-4363-9295-35d6b473981a
components:
  schemas:
    ErrorDetails:
      required:
      - code
      - description
      type: object
      properties:
        code:
          minLength: 1
          type: string
        description:
          minLength: 1
          type: string
        request_id:
          type:
          - string
          - 'null'
x-tagGroups:
- name: Users
  tags:
  - User
- name: Locations
  tags:
  - Location
  - Location profile
  - Location home profile
  - Location price formulas
- name: Meters
  tags:
  - Meter
  - Meter Energy Day
  - Meter Energy High Resolution
  - Meter Energy Reads
  - Meter Energy Period
  - Meter Max Demand
  - Meter Price Formulas
- name: Jobs
  tags:
  - Jobs
- name: Portfolio
  tags:
  - Portfolio Accounts
  - Portfolio Groups
  - Portfolio Locations
  - Portfolio Users
- name: Client details
  tags:
  - Client details
