openapi: 3.2.0
info:
  title: Insights Health API
  version: 3.4.1
  contact:
    name: Insights Team
    email: support_b2b@eliq.com
  description: '# API Reference


    The Eliq insights API is organized around REST.'
servers:
- url: http://localhost:3000
security:
- BearerAuth: []
tags:
- name: Health
paths:
  /v3/health/heart_beat:
    parameters: []
    get:
      summary: Get heart beat
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
              examples:
                Ok response:
                  value: OK
      operationId: get-v3-heartbeat
      parameters: []
      description: Endpoint to check whether the API is up or not. Successful response means the API is up and running, timeouts or 5XX responses would indicate there are issues with the API
      tags:
      - Health
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      description: The Eliq insights API uses bearer tokens to authenticate requests. Read more under Authentication tag.
x-tagGroups:
- name: Authentication
  tags:
  - Authentication
- name: Users
  tags:
  - Users
- name: Locations
  tags:
  - Locations
  - Location Profile
  - Energy Data
  - Energy Usage Categories
  - Energy Performance Certificate
  - Similar Homes
  - Budgets
  - Advice
  - Anomalies
  - Market Price
  - Price Formulas
- name: Eliq Connect
  tags:
  - Eliq Connect
- name: Health
  tags:
  - Health
- name: Deprecated
  tags:
  - Breakdown
  - Home Profile
